export { default as Home } from "./[depr] Home";
export { default as AboutUs } from "./[depr] AboutUs";
export { default as Impact } from "./Impact";
export { default as PatronsAndPartners } from "./PatronsAndPartners";
export { default as Events } from "./Events";
export { default as GetInvolved } from "./GetInvolved";
export { default as NationalCommittee } from "./NationalCommittee";
export { default as PreSelectionDays } from "./PreSelectionDays";
export { default as DaysOfEYP } from "./DaysOfEYP";
export { default as YouthSummit } from "./YouthSummit";
export { default as NationalSession } from "./NationalSession";
export { default as PublicRelations } from "./PublicRelations";
export { default as PressReleases } from "./PressReleases";
